name: Test project
on: push
jobs:
  reactjs-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      
      #Incase if you need any particular custom versions
      - name: Install NodeJS  
        uses: actions/checkout@v4
        with:
          node-version: '18' 

      # We can also use 'npm install' but this might install break version. To avoid that we are using npm ci that will only preferred versions mentioned in package-lock.json file    
      - name: Install dependecies packages
        run: npm ci 
        
      - name: Run npm testing
        run: npm test         